# Generated by Django 4.2.2 on 2023-07-01 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_colorcar_brochure'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfochild',
            name='carinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.carinfo'),
            preserve_default=False,
        ),
    ]
