# Generated by Django 4.2.2 on 2023-07-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carinfochild_carinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
