# Generated by Django 4.2.2 on 2023-07-01 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_brochure_brochure_alter_carinfochild_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochure',
            name='carmodel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel'),
        ),
    ]
