# Generated by Django 4.2.2 on 2023-07-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_carinfochild_carinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carinfo', to='cars.carmodel'),
        ),
    ]
