# Generated by Django 4.2.2 on 2023-07-04 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_carinfo_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorcar',
            name='brochure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carcolor', to='cars.brochure'),
        ),
    ]
