# Generated by Django 4.2.2 on 2023-07-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_colorcar_brochure'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('question', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=25)),
            ],
        ),
    ]
